site_name: linearmoney
site_url: https://grammacc.github.io/linearmoney
docs_dir: md
site_dir: ../docs
theme:
    name: material
    highlightjs: false
extra_css: [syntax-highlighting.css]
use_directory_urls: false
nav:
    - Home: index.md
    - User Guide:
        - Quickstart: quickstart.md
        - Recipes: recipes.md
        - Glossary: glossary.md
        - FAQ: FAQ.md
    - Linear Money Model: linear_money_model.md
    - API Reference: api_reference/linearmoney.html
markdown_extensions:
    - codehilite:
        css_class: language-python
        guess_lang: false
    - fenced_code
    - pymdownx.arithmatex:
        generic: true
    - admonition
    - pymdownx.details

extra_javascript:
    - js/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js



